name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16]

    name: Node ${{ matrix.node }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ga-test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test
        env:
          PGUSER: postgres
          PGHOST: localhost
          PGDB: postgres
          PGPASSWORD: password
          PGPORT: 5432

      - name: Run linter
        run: yarn lint